name: calculator_app
description: A simple calculator app built with Flutter.
publish_to: 'none' # Remove this line if you plan to publish the app
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.0.0 # For voice input (optional)
  cloud_firestore: ^4.0.0 # For Firebase integration (optional)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  